"""
backend/app/compliance/sr117_disclosures.py
=============================================
SR 11-7 / OCC 2011-12 Model Risk Management disclosure injector.

Appends standardised model risk disclosure language to analyst-facing
and briefing-audience outputs.  Applicant-facing communications are
explicitly excluded — SR 11-7 language is a regulatory/internal construct
not appropriate for consumer disclosures.

SR 11-7 (Federal Reserve / OCC) requires that institutions:
  1. Document the limitations and assumptions of each model used in
     credit decisions.
  2. Disclose the identity and version of the model to internal users.
  3. Communicate known performance degradation risks (out-of-sample,
     regime change, data drift).
  4. Ensure validation status is visible to model users.

This module injects a structured SR 11-7 footer block into output
narratives for analyst and briefing audience types.

The footer is human-readable and structured for auditor review.

Usage::

    from app.compliance.sr117_disclosures import Sr117Disclosures

    disclosures = Sr117Disclosures()
    augmented = disclosures.inject(
        narrative=narrative,
        provider_model="gpt-4.1-2025-04-14",
        session_id="abc-123",
        audience="analyst",
    )
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

import structlog

log = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# SR 11-7 boilerplate blocks
# ---------------------------------------------------------------------------

_SEPARATOR = "\n" + ("─" * 72) + "\n"

_HEADER = "MODEL RISK DISCLOSURE (SR 11-7 / OCC 2011-12)"

_LIMITATIONS_TEXT = (
    "This output was generated by a large language model (LLM) grounded "
    "against retrieved policy and data sources.  It is subject to the "
    "following limitations:\n"
    "  • The model may produce plausible but incorrect information outside "
    "the scope of retrieved documents.\n"
    "  • Retrieval quality depends on document freshness; policy documents "
    "may not reflect the most recent regulatory guidance.\n"
    "  • The model has not been independently validated for regulatory "
    "examination purposes.\n"
    "  • Confidence scores are heuristic indicators, not statistical "
    "significance levels.\n"
    "  • Output should be reviewed by a qualified credit analyst before "
    "being used in a credit decision."
)

_VALIDATION_STATUS = (
    "Validation Status: INTERNAL USE — Pending formal model validation. "
    "This model is approved for analytical assistance only. "
    "It is NOT approved as a sole-input credit decision tool."
)

_REGIME_WARNING = (
    "Performance Note: Model performance may degrade under macroeconomic "
    "regime changes not represented in the training or retrieval corpus. "
    "Monitor for distribution shift in input features."
)

_FOOTER_TEMPLATE = (
    "{separator}"
    "{header}\n\n"
    "Session ID  : {session_id}\n"
    "Provider    : {provider_model}\n"
    "Generated   : {timestamp} UTC\n\n"
    "{limitations}\n\n"
    "{validation_status}\n\n"
    "{regime_warning}"
    "{separator}"
)


# ---------------------------------------------------------------------------
# Disclosure injector
# ---------------------------------------------------------------------------

class Sr117Disclosures:
    """
    Injects SR 11-7 model risk disclosure language into analyst/briefing output.

    The disclosure is appended as a clearly-delimited footer block.
    Applicant-audience outputs are returned unchanged.
    """

    # Audience types that should receive the SR 11-7 footer.
    _APPLICABLE_AUDIENCES = frozenset({"analyst", "briefing"})

    def inject(
        self,
        narrative: str,
        provider_model: str,
        session_id: str,
        audience: str,
    ) -> str:
        """
        Inject the SR 11-7 disclosure footer into *narrative* if applicable.

        Args:
            narrative:      The output narrative to augment.
            provider_model: Model identifier (e.g. "gpt-4.1-2025-04-14").
            session_id:     UUID of the copilot session.
            audience:       Output audience — "analyst", "briefing", or "applicant".
                            Only analyst and briefing receive the disclosure.

        Returns:
            The original narrative unchanged (applicant) or with footer appended.
        """
        if audience not in self._APPLICABLE_AUDIENCES:
            log.debug(
                "sr117.skipped",
                audience=audience,
                session_id=session_id,
            )
            return narrative

        footer = self._format_disclosure(provider_model, session_id)
        augmented = narrative.rstrip() + footer

        log.info(
            "sr117.injected",
            audience=audience,
            session_id=session_id,
            provider_model=provider_model,
        )

        return augmented

    def _format_disclosure(
        self,
        provider_model: str,
        session_id: str,
    ) -> str:
        """Build the formatted SR 11-7 footer block."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

        return _FOOTER_TEMPLATE.format(
            separator=_SEPARATOR,
            header=_HEADER,
            session_id=session_id,
            provider_model=provider_model,
            timestamp=timestamp,
            limitations=_LIMITATIONS_TEXT,
            validation_status=_VALIDATION_STATUS,
            regime_warning=_REGIME_WARNING,
        )

    def has_disclosure(self, text: str) -> bool:
        """
        Return True if text already contains an SR 11-7 footer.
        Useful for idempotency checks.
        """
        return _HEADER in text

    # Public alias for tests / direct use
    def format_disclosure(
        self,
        provider_model: str,
        session_id: str,
    ) -> str:
        """Return the raw footer text (without the leading narrative)."""
        return self._format_disclosure(provider_model, session_id)
